"""empty message

Revision ID: 14f239b7c6de
Revises: 
Create Date: 2019-07-06 15:28:43.281265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14f239b7c6de'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rotator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rotator_name', sa.String(length=64), nullable=True),
    sa.Column('azimuth_steps', sa.Integer(), nullable=True),
    sa.Column('azimuth_degrees', sa.Float(), nullable=True),
    sa.Column('elevation_steps', sa.Integer(), nullable=True),
    sa.Column('elevation_degrees', sa.Float(), nullable=True),
    sa.Column('polarity_steps', sa.Integer(), nullable=True),
    sa.Column('polarity_degrees', sa.Float(), nullable=True),
    sa.Column('polarity_is_tracking', sa.Boolean(), nullable=True),
    sa.Column('polarity_tracking_speed', sa.Numeric(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rotator_name')
    )
    op.create_table('rotator_command',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rotator_id', sa.Integer(), nullable=True),
    sa.Column('issue_time', sa.DateTime(), nullable=True),
    sa.Column('execution_time', sa.DateTime(), nullable=True),
    sa.Column('command_code', sa.Integer(), nullable=True),
    sa.Column('command_value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['rotator_id'], ['rotator.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###




def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rotator_command')
    op.drop_table('rotator')
    # ### end Alembic commands ###
